fix Generate policies of ci

diff --git a/.github/workflows/update_policies.yml b/.github/workflows/update_policies.yml
--- a/.github/workflows/update_policies.yml
+++ b/.github/workflows/update_policies.yml
@@ -17,7 +17,13 @@ jobs:
           go-version: ${{ env.GO_VERSION }}
           cache: false
       - name: Generate policies
-        run: make gen-policies
+        run: |
+          set -e
+          make gen-policies
+          if [ $? -ne 0 ]; then
+            echo "Policy generation failed"
+            exit 1
+          fi
         working-directory: api
       - name: Authenticate to Google Cloud
         uses: google-github-actions/auth@v1
